name: PHPUnit

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Or your desired PHP version
        #extensions: xdebug # Required for code coverage
        ini-values: memory_limit=-1 # Adjust as needed

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHPUnit tests with coverage
      run: vendor/bin/phpunit